In [1]:
import numpy as np

#### 1.1 用list构造并指定数据类型

In [2]:
array = np.array([[1,2,3], [2,3,4]], dtype=np.int32)
array

array([[1, 2, 3],
       [2, 3, 4]], dtype=int32)

#### 1.2 全1/全0数组

In [3]:
np.ones((3, 2))   # 指定数组形状

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
np.zeros_like(array)   # 生成和另外某个数组形状一样的数组

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

#### 1.3 生成均匀分布数组

In [5]:
np.arange(2, 14, 2)   # 指定首、尾、步长

array([ 2,  4,  6,  8, 10, 12])

In [6]:
np.linspace(0, 2, 9)   # 指定首、尾、数量

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

#### 1.4 生成随机数

In [7]:
np.random.rand(2,2)   # 输入矩阵形状, 生成 [0,1] 均匀分布

array([[0.1970065 , 0.01865571],
       [0.75438964, 0.94095424]])

In [8]:
np.random.randn(2,2)   # 输入矩阵形状, 生成标准正态分布

array([[ 0.80566648, -0.22305744],
       [-0.66760313,  0.34183701]])

In [9]:
np.random.randint(0, 10, (2, 2))  # 生成形状为(2,2)的 [0, 10) 间随机整数数组

array([[9, 9],
       [8, 9]])

#### 1.5 生成指定分布

In [10]:
np.random.normal(2, 10, size=(2,2)) # 生成均值为2, 标准差为10的正态分布

array([[11.33465628, 13.74903844],
       [13.36065686, 18.39827446]])

In [11]:
np.random.binomial(1, 0.5, (1, 10))   # n=1, p=0.5的二项分布

array([[1, 0, 0, 0, 0, 1, 1, 1, 0, 1]])

In [12]:
np.random.uniform(1, 3, (1, 5))        # [1, 3]的均匀分布

array([[2.62815787, 2.23839993, 1.98509703, 1.92195896, 2.16378126]])

In [13]:
np.random.poisson(2, (1, 10))         # λ = 2 的泊松分布

array([[1, 2, 2, 1, 3, 6, 0, 2, 1, 2]])

#### 1.6 随机全排列

In [14]:
np.random.permutation(10)    # 生成 0~9 的一个随机排列

array([2, 5, 6, 7, 0, 4, 8, 3, 9, 1])

In [15]:
np.random.permutation([1,2,3,4,5])   # 生成输入数组的一个随机排列

array([3, 1, 5, 2, 4])

#### 1.7 对角矩阵

In [16]:
np.diag((1,2,3,4,5,6,7,8,9))

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])