In [1]:
import numpy as np

#### 2.1 数组属性

In [2]:
array = np.random.normal(0, 5, size=(2, 5, 5))

维度

In [3]:
array.ndim

3

形状

In [4]:
array.shape

(2, 5, 5)

#### 2.2 元素属性

元素数量

In [5]:
array.size

50

元素类型

In [6]:
array.dtype

dtype('float64')

每个元素的大小，以字节为单位

In [7]:
array.itemsize

8

#### 2.3 统计属性

求和

In [8]:
array.sum()    # 比python自带sum快很多

-14.2170722998952

最小值

In [9]:
array.min()

-8.825783561961089

最大值

In [10]:
array.max()

11.689669038408734

均值

In [11]:
array.mean()

-0.284341445997904

中位数

In [12]:
np.median(array)

0.15530062601512187

方差

In [13]:
array.var()

24.29138589153458

标准差

In [14]:
array.std()

4.9286292101896425

0.9分位数

In [15]:
np.percentile(array, 90)
np.quantile(array, 0.9)

5.982011326247881

元素乘积

In [16]:
array.prod()

-8.571313892724762e+16

#### 2.3 指定维度
以上操作大都可以指定维度

In [17]:
array.sum(axis=1)

array([[ -4.34961195, -23.40381957, -15.00669427,   3.09969281,
         14.52908688],
       [ -2.72507651,  14.52106409,  -1.8827053 ,  -0.34742242,
          1.34841394]])

In [18]:
array.std(axis=2)

array([[5.04471416, 5.32935682, 4.12293112, 3.04641513, 4.5000143 ],
       [4.41875704, 3.63916665, 5.83785514, 1.6833666 , 5.20131701]])

In [19]:
np.quantile(array, 0.9, axis=0)

array([[ 1.35022475, -4.37880533, -0.4171714 ,  5.87746023,  6.78552263],
       [ 1.22353225,  2.21912293,  1.94265552, -6.79729504,  5.4580924 ],
       [ 1.32273225,  9.82047415, -0.36389217,  2.14473247,  0.68218578],
       [ 7.91676225,  1.03819572,  1.3285014 ,  1.76122798,  0.30421485],
       [-3.0500164 ,  3.07877394, -0.65899524,  5.86641365,  8.22756786]])