In [1]:
import numpy as np

#### 3.1 四则运算

In [2]:
array = np.array([[1,2,3], [4,5,6]])

In [3]:
array + array

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [4]:
array + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [5]:
array * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [6]:
array / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

#### 3.2 舍入函数

In [7]:
array = np.random.normal(size=(2, 2))
array

array([[ 1.29951885, -2.44958893],
       [ 0.65795063,  0.18938231]])

In [8]:
np.around(array, 3)     # 保留三位小数

array([[ 1.3  , -2.45 ],
       [ 0.658,  0.189]])

#### 3.3 数据截断

In [15]:
array = np.random.randint(-10, 20, 10)
array

array([-3,  9, 12, 16,  2,  3, 13,  1, 12, 14])

In [16]:
array.clip(0, 10)  # 将数据截断在 [0, 10]内

array([ 0,  9, 10, 10,  2,  3, 10,  1, 10, 10])

#### 3.4 矩阵运算

In [7]:
a = np.array([[1, 1, 1], [2, 2, 2]])
b = np.array([[1, 1], [2, 2], [3, 3]])

矩阵乘法
* matmul和dot二者都是矩阵乘法。
* np.matmul中禁止矩阵与标量的乘法。
* 在矢量乘矢量的內积运算中，np.matmul与np.dot没有区别。
* np.matmul中，多维的矩阵，将前n-2维视为后2维的元素后，进行乘法运算。

In [8]:
np.dot(a, b)

array([[ 6,  6],
       [12, 12]])

In [9]:
np.matmul(a,b)

array([[ 6,  6],
       [12, 12]])

对应元素相乘

In [24]:
a * b.reshape((2, 3))

array([[1, 1, 2],
       [4, 6, 6]])

In [25]:
np.multiply(a, b.reshape((2, 3)))

array([[1, 1, 2],
       [4, 6, 6]])

向量内积

In [21]:
v1 = np.array([1,2,1])
v2 = np.array([2,0,2])
np.dot(v1, v2)

4

向量外积

In [38]:
v1 = np.array([1,2,1])
v2 = np.array([2,0,2])
np.outer(v1, v2)

array([[2, 0, 2],
       [4, 0, 4],
       [2, 0, 2]])

求模

In [22]:
np.linalg.norm(a)

3.872983346207417

#### 3.5 矩阵变换

求逆

In [39]:
np.invert(a)

array([[-2, -2, -2],
       [-3, -3, -3]])

转置

In [11]:
a.T

array([[1, 2],
       [1, 2],
       [1, 2]])

In [12]:
a.transpose()

array([[1, 2],
       [1, 2],
       [1, 2]])

矩阵变形

In [26]:
a.reshape((3, 2))

array([[1, 1],
       [1, 2],
       [2, 2]])

交换两个维度的顺序

In [19]:
c = np.array([[[1, 1, 1], [2, 2, 2]]])
c.shape

(1, 2, 3)

In [20]:
c.transpose(1, 0, 2).shape

(2, 1, 3)

平铺

In [31]:
np.tile(a, [1, 2])

array([[1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2]])

In [30]:
np.tile(a, [2, 1])

array([[1, 1, 1],
       [2, 2, 2],
       [1, 1, 1],
       [2, 2, 2]])