In [1]:
import numpy as np

#### 4.1 特征值和特征向量

In [3]:
a = np.diag((1,2,3,4,5,6,7,8,9))
np.linalg.eig(a)

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1.]]))

#### 4.2 行列式

In [9]:
a = np.array([[1, 2], [3, 1]], dtype=np.int32)
np.linalg.det(a)

-5.000000000000001

#### 4.3 奇异值分解

In [11]:
a = np.random.randint(-10,10, (4, 3))
a

array([[ 9, -8, -2],
       [-7, -2, -9],
       [-7, -6,  4],
       [ 2,  8, -3]])

In [13]:
u, s, vh = np.linalg.svd(a) 
u.shape, s.shape, vh.shape

((4, 4), (3,), (3, 3))

In [14]:
u, s, vh

(array([[-0.703249  , -0.4436327 ,  0.47678435,  0.28514481],
        [ 0.59368752, -0.10830162,  0.79655261, -0.03619146],
        [ 0.39041165, -0.59449807, -0.34395725,  0.61306133],
        [-0.02355244,  0.66184049,  0.14097528,  0.73589294]]),
 array([13.59819495, 13.06803183, 10.26234078]),
 array([[-0.97550007,  0.1402927 , -0.16946262],
        [ 0.17222062,  0.96627995, -0.19142391],
        [ 0.13689296, -0.21591899, -0.96676745]]))

#### 4.4 近似相等
* allclose() 用于匹配两个数组，并得到布尔值表示的输出。
* 如果在一个公差范围内（within a tolerance）两个数组不等同，则 allclose() 返回 False。
* 该函数对于检查两个数组是否相似非常有用。

In [15]:
np.allclose([1e10,1e-7], [1.00001e10,1e-8])

False

In [16]:
np.allclose([1e10,1e-8], [1.00001e10,1e-9])

True

In [17]:
np.allclose([1.0, np.nan], [1.0, np.nan])

False

In [18]:
np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)

True