In [1]:
import numpy as np

In [2]:
array = np.random.randint(0, 100, (10))
array

array([81,  4, 35, 69,  1, 77, 63, 77, 41, 10])

#### 5.1 对应位置元素是否相等

In [3]:
array < 50

array([False,  True,  True, False,  True, False, False, False,  True,
        True])

In [4]:
(array < 50) & (array > 20)

array([False, False,  True, False, False, False, False, False,  True,
       False])

In [5]:
array == array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

#### 5.2 按值对索引排序

In [6]:
array.argsort()    # 默认升序

array([4, 1, 9, 2, 8, 6, 3, 5, 7, 0])

#### 5.3 topK个数的索引
* 类似于快排
* 对于传入的数组a，先用O(n)复杂度求出第k大的数字，然后利用这个第k大的数字将数组a划分成两半

In [7]:
np.argpartition(array, -4)[-4:]

array([3, 7, 5, 0])

#### 5.4 提取特定元素

In [8]:
cond = (array < 50) & (array > 20)
np.extract(cond, array)

array([35, 41])

#### 5.5 查找满足条件的元素位置

In [9]:
np.where(array < 50)

(array([1, 2, 4, 8, 9]),)